### ISSUE TITLE
Create a specific LocalNotification to silent

### ISSUE THREAD

**Issue by Bharath-itero** [BharathKumar-c/rn-schedule-notifications#2]
First, I created a notification channel that has default parameters except for the soundName

PushNotification.createChannel({
	channelId: `My_Channel`, // (required)
	channelName: `Test_Channel`, // (required)
	soundName: null, // (optional) See `soundName` parameter of `localNotification` function
	vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
});
then I show a specific notification and I want it to be silent one

PushNotification.localNotification({
  /* iOS and Android properties */
  channelId: `My_Channel`,
  title: 'Test Notification',
  message: 'Test', 
  playSound: false, 
  soundName: null 
});
I already set the playSound and soundName into false and null but whenever I receive a notification it plays a default notification sound. How do I make that specific notication silent?

**Comment by BharathKumar-c** [comment]
you should set playSound : false in createChannel
